# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('day_start_time', models.TimeField(default=datetime.time(8, 0), verbose_name=b'Day Start Time')),
                ('day_end_time', models.TimeField(default=datetime.time(23, 0), verbose_name=b'Day End Time')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('et_type', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTypeShiftError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_time', models.TimeField(verbose_name=b'Error Time')),
                ('error_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Date')),
                ('error_emp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.EmployeeType')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name=b'Last Name')),
                ('person_min_hours_per_week', models.IntegerField(default=25, verbose_name=b'Min Hrs / Week')),
                ('person_max_hours_per_week', models.IntegerField(default=40, verbose_name=b'Min Hrs / Week')),
                ('person_min_hours_per_shift', models.IntegerField(default=4, verbose_name=b'Min Hrs / Shift')),
                ('person_max_hours_per_shift', models.IntegerField(default=8, verbose_name=b'Min Hrs / Shift')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Person')),
                ('pet_employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.EmployeeType')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqst_date_date', models.DateField()),
                ('rqst_date_start_time', models.TimeField(default=datetime.time(0, 0), verbose_name=b'Request Start Time')),
                ('rqst_date_end_time', models.TimeField(default=datetime.time(23, 59), verbose_name=b'Request End Time')),
                ('rqst_date_type', models.CharField(choices=[(b'VACA', b'Vacation'), (b'SICK', b'Sick'), (b'PREF', b'Preferred'), (b'SKIP', b'Cannot Work')], max_length=4)),
                ('rqst_date_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
                ('rqst_day_type', models.CharField(choices=[(b'PREF', b'Preferred'), (b'SKIP', b'Cannot Work')], max_length=4)),
                ('rqst_day_start_time', models.TimeField(default=datetime.time(0, 0), verbose_name=b'Request Start Time')),
                ('rqst_day_end_time', models.TimeField(default=datetime.time(23, 59), verbose_name=b'Request End Time')),
                ('rqst_day_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqmt_date_date', models.DateField(default=b'2016-03-17', verbose_name=b'Effective Date')),
                ('rqmt_date_time', models.TimeField(default=datetime.time(8, 0), verbose_name=b'Effective Time')),
                ('rqmt_date_employee_count', models.PositiveIntegerField(default=0, verbose_name=b'Count')),
                ('rqmt_date_employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.EmployeeType')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
                ('rqmt_day_start_time', models.TimeField(default=datetime.time(0, 0), verbose_name=b'Effective Time')),
                ('rqmt_day_employee_count', models.PositiveIntegerField()),
                ('rqmt_day_employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.EmployeeType')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name=b'Start Time')),
                ('end_time', models.TimeField(verbose_name=b'End Time')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Person')),
                ('shift_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Date')),
                ('shift_employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.EmployeeType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requirementdaytime',
            unique_together=set([('day_of_week', 'rqmt_day_start_time', 'rqmt_day_employee_type', 'rqmt_day_employee_count')]),
        ),
        migrations.AlterUniqueTogether(
            name='requirementdatetime',
            unique_together=set([('rqmt_date_date', 'rqmt_date_time', 'rqmt_date_employee_type', 'rqmt_date_employee_count')]),
        ),
        migrations.AlterUniqueTogether(
            name='requestdaytime',
            unique_together=set([('day_of_week', 'rqst_day_start_time', 'rqst_day_type')]),
        ),
    ]
