# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160321_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_max_hours_per_shift',
            field=models.PositiveIntegerField(default=8, verbose_name=b'Max Hrs / Shift'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_max_hours_per_week',
            field=models.PositiveIntegerField(default=40, verbose_name=b'Max Hrs / Week'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_min_hours_per_shift',
            field=models.PositiveIntegerField(default=4, verbose_name=b'Min Hrs / Shift'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_min_hours_per_week',
            field=models.PositiveIntegerField(default=25, verbose_name=b'Min Hrs / Week'),
        ),
    ]
