# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160325_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetypeshifterror',
            name='error_time',
        ),
        migrations.AddField(
            model_name='employeetypeshifterror',
            name='error_end_time',
            field=models.TimeField(default=datetime.time(2, 27, 48, 845947), verbose_name=b'Error End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetypeshifterror',
            name='error_start_time',
            field=models.TimeField(default=datetime.time(2, 28, 9, 447339), verbose_name=b'Error Start Time'),
            preserve_default=False,
        ),
    ]
